# Generated by Django 4.0.7 on 2022-09-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_actioncause_referencedocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Profile_Img',
        ),
    ]
